In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv("dataIPKmahasiswa.csv")
x = dataset.iloc[:, [2,3]].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)

[[2.76 2.8 ]
 [3.   3.3 ]
 [3.5  3.3 ]
 [3.17 3.41]
 [2.9  2.89]
 [2.95 2.82]
 [2.76 3.14]
 [2.62 2.89]
 [3.6  3.54]
 [2.71 2.55]
 [3.14 3.46]
 [2.67 2.3 ]
 [2.57 2.82]
 [2.71 3.  ]
 [3.24 3.38]
 [2.86 2.86]
 [2.71 3.27]
 [2.67 2.2 ]
 [2.67 2.68]
 [3.1  3.71]
 [3.   3.33]
 [3.12 3.23]
 [2.9  3.32]
 [2.95 3.41]
 [3.05 2.92]
 [2.64 3.  ]
 [2.45 2.45]
 [0.33 2.9 ]
 [3.33 3.63]
 [2.52 2.7 ]
 [3.05 3.38]
 [2.81 3.09]
 [2.52 2.75]
 [3.12 3.1 ]
 [2.86 3.05]
 [3.05 3.27]
 [2.71 3.16]
 [2.88 3.32]
 [2.76 3.25]
 [2.69 2.59]
 [2.29 3.09]
 [2.71 2.59]
 [2.43 3.02]
 [2.88 2.59]
 [2.07 2.59]
 [3.1  3.  ]
 [2.57 2.55]
 [3.26 3.73]
 [2.71 2.89]
 [1.9  1.91]
 [2.24 1.68]
 [2.52 2.27]
 [2.86 2.8 ]
 [2.76 3.09]
 [2.57 2.82]
 [2.14 1.55]
 [2.48 2.95]
 [2.33 1.84]
 [2.1  2.5 ]
 [2.88 3.48]
 [2.81 3.11]
 [2.6  2.91]
 [2.76 2.95]
 [2.86 3.43]
 [3.02 3.63]
 [2.57 3.39]
 [3.31 3.6 ]
 [3.   3.23]
 [2.48 2.48]
 [2.52 2.8 ]
 [2.76 3.18]
 [2.57 3.16]
 [2.6  3.32]
 [2.67 2.18]
 [2.86 2.82]
 [3.   3.5 ]
 [2.05 1.68]

In [5]:
print(y)

[3.07 3.17 3.54 3.41 3.09 3.07 3.06 2.91 3.4  2.2  3.44 2.4  2.45 2.57
 3.45 3.04 3.19 2.95 2.11 3.38 3.29 3.19 3.11 3.2  3.09 3.08 2.32 3.23
 3.52 3.   3.25 3.1  2.86 3.07 3.06 3.1  3.07 3.16 3.07 3.03 2.96 3.09
 2.9  3.03 2.77 3.17 2.94 3.24 3.2  2.66 2.14 2.72 2.91 3.05 2.97 2.31
 2.73 2.45 2.85 3.15 3.27 2.92 2.93 2.9  3.36 3.   3.6  3.22 2.63 2.9
 3.06 3.1  3.16 2.32 3.02 2.67 2.33 2.63 3.42 2.38 2.9  3.39 1.71 2.31
 2.62 2.76 3.3  1.39 2.63 2.79 2.92 2.49 1.82 3.63 2.18 2.81 2.71 2.83
 2.53 2.74 2.92 2.9  3.59 2.98 3.   3.64 3.8  3.37 3.02 2.27 2.75 2.75
 3.69 3.37 2.89 3.04 2.64 3.57 2.65 2.97 2.14 1.08 2.48 2.79 3.28 3.41
 3.56 3.37 1.36 2.63 2.52 3.44 2.7  3.12 3.66 3.35 2.3  3.24 2.53 2.94
 2.47 2.47 3.15 2.26 3.38 3.35 3.04 2.63 1.87 2.95 2.49 3.3  3.03 3.04
 3.31 3.43 2.44 2.57 2.47 2.66 2.98 3.22 2.64 2.78 2.89 2.93 2.89 3.02
 2.71 2.84 3.17 3.27 1.93 2.53 2.86 3.35 2.65 3.01 2.97 2.73 3.29 3.22
 2.88 2.41 3.08 3.23 2.81 2.65 2.94 2.   1.57 2.82 2.59 3.11 2.14 3.43
 2.94 2

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test, = train_test_split(x, y, test_size=0.25, random_state=0)

In [7]:
print(x_train)

[[2.4  2.66]
 [3.33 2.6 ]
 [2.45 1.43]
 [2.93 2.25]
 [2.76 2.58]
 [3.26 3.38]
 [2.86 2.98]
 [2.43 2.14]
 [2.9  3.32]
 [3.45 2.9 ]
 [3.64 3.96]
 [3.33 3.05]
 [3.05 2.98]
 [3.1  3.06]
 [3.31 3.6 ]
 [3.33 2.48]
 [2.57 2.82]
 [2.71 3.41]
 [2.98 2.43]
 [3.02 2.58]
 [2.6  1.93]
 [3.1  2.8 ]
 [2.67 2.2 ]
 [3.17 2.7 ]
 [3.05 3.05]
 [3.   2.83]
 [2.83 2.08]
 [3.52 3.46]
 [2.76 2.53]
 [2.5  2.17]
 [3.4  3.03]
 [2.57 2.91]
 [2.86 3.14]
 [3.29 2.58]
 [2.21 2.39]
 [2.64 2.25]
 [2.93 2.89]
 [2.24 2.03]
 [2.95 2.08]
 [3.45 3.15]
 [2.36 2.48]
 [3.24 3.46]
 [3.36 3.4 ]
 [3.02 3.03]
 [2.95 2.84]
 [2.83 3.11]
 [2.69 2.36]
 [3.12 3.1 ]
 [3.02 2.88]
 [2.86 3.05]
 [2.98 2.66]
 [2.62 3.02]
 [2.17 2.66]
 [3.45 2.98]
 [2.71 2.41]
 [3.43 2.95]
 [2.83 3.16]
 [3.1  2.89]
 [3.12 2.83]
 [2.88 2.71]
 [2.57 2.55]
 [3.26 3.27]
 [2.79 2.44]
 [3.   2.89]
 [2.67 2.18]
 [2.86 3.36]
 [2.79 2.73]
 [2.81 1.92]
 [2.74 2.75]
 [2.52 2.7 ]
 [2.98 3.18]
 [2.52 2.27]
 [2.6  2.2 ]
 [3.1  3.38]
 [0.33 2.9 ]
 [3.   3.08]
 [3.07 2.65]

In [8]:
print(x_test)

[[2.88 2.81]
 [2.98 2.2 ]
 [3.57 3.54]
 [3.19 2.9 ]
 [2.36 2.25]
 [3.24 3.58]
 [3.05 3.23]
 [2.57 3.39]
 [2.5  2.67]
 [3.1  3.  ]
 [2.83 2.59]
 [2.88 2.77]
 [2.83 3.02]
 [2.64 2.83]
 [2.62 2.43]
 [2.88 3.48]
 [2.36 2.  ]
 [3.21 2.85]
 [2.57 2.82]
 [2.9  2.89]
 [2.29 2.89]
 [3.02 2.55]
 [2.76 2.58]
 [1.98 2.5 ]
 [3.5  3.5 ]
 [2.81 2.94]
 [2.9  2.67]
 [2.95 2.53]
 [3.21 3.39]
 [3.6  3.5 ]
 [3.31 2.96]
 [2.76 3.14]
 [3.   3.3 ]
 [2.4  2.64]
 [2.88 3.32]
 [3.43 3.56]
 [2.81 2.86]
 [2.33 2.65]
 [2.48 2.48]
 [3.5  3.23]
 [3.14 3.46]
 [2.45 2.45]
 [2.81 3.11]
 [2.55 2.75]
 [2.17 2.66]
 [3.19 3.19]
 [2.86 2.41]
 [2.86 2.86]
 [2.86 2.8 ]
 [3.52 3.48]
 [2.95 2.82]
 [2.45 3.11]
 [2.05 1.68]
 [2.62 2.89]
 [2.48 2.32]
 [2.76 1.44]
 [1.79 2.24]
 [2.69 2.58]
 [3.02 3.42]
 [3.   3.33]
 [3.1  3.04]
 [2.31 2.25]
 [2.83 2.53]
 [3.29 3.71]
 [2.86 2.82]
 [3.21 3.07]
 [3.45 3.13]
 [3.02 3.63]
 [2.14 1.55]
 [3.4  3.23]
 [3.4  2.78]
 [2.43 2.55]
 [2.67 2.66]
 [3.19 3.08]
 [2.55 2.55]
 [2.48 2.95]
 [3.6  3.54]

In [9]:
print(y_train)

[2.85 2.73 1.82 2.81 2.92 3.16 3.21 2.48 3.11 3.12 3.8  3.49 3.28 2.16
 3.6  3.35 2.45 2.9  2.62 3.17 2.41 2.53 2.95 2.75 3.15 3.37 2.89 3.43
 2.89 2.47 3.28 2.98 0.92 3.14 2.47 2.64 3.09 2.14 2.64 3.56 2.72 3.58
 3.56 3.38 3.07 3.27 3.12 3.07 3.1  3.06 1.9  2.83 2.76 3.29 3.03 3.35
 3.3  3.11 3.22 3.02 2.94 3.28 2.71 2.88 2.32 3.24 2.87 2.61 2.97 3.
 3.52 2.72 2.7  3.05 3.23 2.92 3.13 2.44 2.96 2.83 2.53 3.58 2.82 1.72
 3.33 3.1  3.15 2.68 1.02 3.26 2.77 2.93 2.63 3.63 2.75 2.89 3.31 2.34
 2.54 2.11 3.1  2.38 3.37 3.15 3.1  3.15 2.94 2.92 2.88 2.98 3.   3.22
 2.31 2.   3.03 2.65 3.42 3.04 3.2  2.65 2.75 2.95 2.57 3.03 3.19 2.81
 2.67 2.27 2.9  3.33  nan 2.94 2.79 3.09 2.71 3.45 2.92 3.22 2.83 2.14
 3.31 3.23 2.97 3.38 3.32 2.96 3.69 2.57 3.37 3.01 2.79 3.41 3.54 3.41
 3.09 3.25 2.63 3.06 2.94 3.08 2.82 2.86 2.81 2.39 2.88 3.63 2.9  3.1
 2.4  2.92 3.3  3.07 0.87 2.85 3.09 2.14 3.22 2.93 3.24 3.   2.79 3.2
 2.93 3.35 2.52 2.65 3.2  3.03 3.07 3.02 2.75 2.53 2.97 3.45 2.18 3.37
 2.81 3.5 

In [10]:
print(y_test)

[3.04 2.12 3.25 3.08 2.22 3.42 3.13 3.   2.65 3.17 3.02 3.31 3.33 2.3
 2.53 3.15 2.73 3.02 2.97 3.36 2.85 3.27 2.91 0.99 3.66 3.04 2.94 2.94
 3.22 3.39 3.32 3.06 3.17 2.96 3.16 3.59 2.49 2.7  2.63 3.51 3.44 2.32
 3.27 2.46 2.57 1.64 2.98 3.04 2.91 3.56 3.07 2.92 2.33 2.91 2.73 2.53
 2.72 3.15 3.49 3.29 3.28 2.87 2.85 3.24 3.02 3.09 3.62 3.36 2.31 3.16
 3.18 2.9  2.81 3.09 2.99 2.73 3.4  1.57 2.52 2.82 2.89 3.35 2.97 2.9
 3.02 3.85 3.39 2.83 2.92 2.79 2.66 3.19 3.43 2.47 2.66]


In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [12]:
print(x_train)

[[-1.10900571e+00 -2.98209612e-01]
 [ 1.15285211e+00 -4.26627398e-01]
 [-9.87400451e-01 -2.93077422e+00]
 [ 1.80010039e-01 -1.17573115e+00]
 [-2.33447843e-01 -4.69433327e-01]
 [ 9.82604750e-01  1.24280382e+00]
 [ 9.76267575e-03  3.86685246e-01]
 [-1.03604255e+00 -1.41116376e+00]
 [ 1.07046883e-01  1.11438603e+00]
 [ 1.44470474e+00  2.15461532e-01]
 [ 1.90680472e+00  2.48417575e+00]
 [ 1.15285211e+00  5.36505997e-01]
 [ 4.71862661e-01  3.86685246e-01]
 [ 5.93467921e-01  5.57908961e-01]
 [ 1.10421001e+00  1.71366903e+00]
 [ 1.15285211e+00 -6.83462970e-01]
 [-6.95547828e-01  4.42378171e-02]
 [-3.55053102e-01  1.30701271e+00]
 [ 3.01615298e-01 -7.90477792e-01]
 [ 3.98899506e-01 -4.69433327e-01]
 [-6.22584673e-01 -1.86062601e+00]
 [ 5.93467921e-01  1.43188846e-03]
 [-4.52337310e-01 -1.28274597e+00]
 [ 7.63715284e-01 -2.12597755e-01]
 [ 4.71862661e-01  5.36505997e-01]
 [ 3.50257402e-01  6.56407814e-02]
 [-6.32004799e-02 -1.53958154e+00]
 [ 1.61495210e+00  1.41402753e+00]
 [-2.33447843e-01 -5

In [13]:
print(x_test)

[[ 5.84047795e-02  2.28348528e-02]
 [ 3.01615298e-01 -1.28274597e+00]
 [ 1.73655736e+00  1.58525125e+00]
 [ 8.12357387e-01  2.15461532e-01]
 [-1.20628992e+00 -1.17573115e+00]
 [ 9.33962647e-01  1.67086311e+00]
 [ 4.71862661e-01  9.21759354e-01]
 [-6.95547828e-01  1.26420678e+00]
 [-8.65795191e-01 -2.76806648e-01]
 [ 5.93467921e-01  4.29491175e-01]
 [-6.32004799e-02 -4.48030362e-01]
 [ 5.84047795e-02 -6.27770045e-02]
 [-6.32004799e-02  4.72297104e-01]
 [-5.25300465e-01  6.56407814e-02]
 [-5.73942569e-01 -7.90477792e-01]
 [ 5.84047795e-02  1.45683346e+00]
 [-1.20628992e+00 -1.71080526e+00]
 [ 8.60999491e-01  1.08446710e-01]
 [-6.95547828e-01  4.42378171e-02]
 [ 1.07046883e-01  1.94058567e-01]
 [-1.37653728e+00  1.94058567e-01]
 [ 3.98899506e-01 -5.33642220e-01]
 [-2.33447843e-01 -4.69433327e-01]
 [-2.13048989e+00 -6.40657041e-01]
 [ 1.56631000e+00  1.49963939e+00]
 [-1.11842584e-01  3.01073389e-01]
 [ 1.07046883e-01 -2.76806648e-01]
 [ 2.28652143e-01 -5.76448148e-01]
 [ 8.60999491e-01  1

In [18]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier = (x_train, x_test)

In [26]:
y_pred = classifier.predict(x_test)

AttributeError: ignored